### ISSUE TITLE
unmodifiableView has been removed from Dart 3.5.0

### ISSUE THREAD

**Issue by ReinisSprogis** [renggli/dart-data#5]
Hi. 
Seems like unmodifiableView has been removed from starting from dart 3.5.0 . This breaks data package. 

"The unmodifiable view classes for typed data have been removed (https://github.com/dart-lang/sdk/issues/53218). Instead of using the constructors of these classes, use the new asUnmodifiableView methods on typed data lists."
https://dart.dev/resources/breaking-changes

**Comment by renggli** [comment]
This was fixed in c3fd9d2622832f144b55b63749407afb48b50fbe (May 19, 2024). And has been pushed in 62e523ffffd8d2fd6589ba9e9711dccc9853ed4c (Sep 1, 2024) to [pub.dart.dev](https://pub.dev/packages/data) as `data 0.13.0`.

Let me know if I missed something?

**Comment by ReinisSprogis** [comment]
Oh. Ok. I  think I see where I have a problem. Flutter uses collection: 1.18.0 So this package is incompatible. 
```Because every version of flutter from sdk depends on collection 1.18.0 and data >=0.13.0 depends on collection ^1.19.0, flutter from sdk is incompatible with data >=0.13.0.```

If I downgrade to 0.12.0 then I get errors on all data types like this. Because latest Dart doesn't have them anymore. 
```
 ../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/data-0.12.0/lib/src/type/impl/float.dart(76,7): error GE5CFE876: The method 'UnmodifiableFloat32ListView' isn't defined for the 
class 'Float32DataType'. 
```

So one way to resolve this I think is to downgrade dart and use data: 0.12.0  with flutter. Or I could fork it and downgrade collection package to 1.18.0

**Comment by renggli** [comment]
Maybe easier for you would be to force this package to depend on `collection 1.18.0` with [dependency overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides), if that works without changes to code?

Unfortunately it is very difficult / time-consuming for me to test compatibility with older dependencies, so I typically just pick the latest public version. Not sure if there is a better way, because this seems to be a very common problem?

**Comment by ReinisSprogis** [comment]
It makes sense to use latest. Flutter should upgrade to latest too. Until then ill use forked version.  I did not manage to override package version like you suggested. Thanks for this package!

**Comment by ReinisSprogis** [comment]
Finally got it working.
Need to pull this data package and more package. 
Change in both to collection: 1.18.0 
And meta packages to 1.15.0
This is how to get it working until flutter upgrades it's packages. 
Project working with no issues, but I am using only Levenberg-Marquardt so I don't know if it breaks anything else.
